version: '3'

services:
    web:
        container_name: symfony_tdd
        image: nxswesolowski/ubuntu-php:7.2
        volumes:
            - ./:/var/www
        ports:
            - 8080:80
            - "2222:22"
